# Docker Compose script to run both microservices (web, graph) locally.
# Use of this script:
#   docker compose -f docker/docker-compose-with-rdflib.yml up
#   docker compose -f docker/docker-compose-with-rdflib.yml down   (in a second terminal window)
# Chris Joakim, Microsoft

services:

  web_app:
    image: cjoakim/caig_web_v2:latest
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_ACA_ENVIRONMENT_NAME: "caig-aca-poc-001"
      CAIG_AZURE_MONGO_VCORE_CONN_STR: ""
      CAIG_AZURE_OPENAI_COMPLETIONS_DEP: "gpt-4o"
      CAIG_AZURE_OPENAI_EMBEDDINGS_DEP: "text-embedding-3-small"
      CAIG_AZURE_OPENAI_KEY: "8a431f0899c740508a8ae5eb19284f8c"
      CAIG_AZURE_OPENAI_URL: "https://aoai-poc-eastus2-01.openai.azure.com/"
      CAIG_AZURE_REGION: "eastus2"
      CAIG_CONFIG_CONTAINER: "config"
      CAIG_CONVERSATIONS_CONTAINER: "conversations"
      CAIG_COSMOSDB_NOSQL_ACCT: "cosmos-caig-poc-991"
      CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM: "key"
      CAIG_COSMOSDB_NOSQL_KEY1: "RmYKIdpIPQHIJOydtgIM592xPpapB1N1E0rGf67EPt4WveWcnrUBvduU0Lu5nLuaptqBB1fylfJpACDbMOR9Gw=="
      CAIG_COSMOSDB_NOSQL_RG: "rg-caig-poc-001"
      CAIG_COSMOSDB_NOSQL_URI: "https://cosmos-caig-poc-991.documents.azure.com:443/"
      CAIG_DEFINED_AUTH_USERS: ""
      CAIG_ENCRYPTION_SYMMETRIC_KEY: ""
      CAIG_FEEDBACK_CONTAINER: "feedback"
      CAIG_GRAPH_NAMESPACE: ""
      CAIG_GRAPH_SERVICE_NAME: ""
      CAIG_GRAPH_SERVICE_PORT: "8001"
      CAIG_GRAPH_SOURCE_CONTAINER: "libraries"
      CAIG_GRAPH_SOURCE_DB: "caig"
      CAIG_GRAPH_SOURCE_OWL_FILENAME: ""
      CAIG_GRAPH_SOURCE_RDF_FILENAME: ""
      CAIG_GRAPH_SOURCE_TYPE: "cosmos_nosql"
      CAIG_LA_WORKSPACE_NAME: ""
      CAIG_LOG_LEVEL: "debug"
      CAIG_WEBSVC_AUTH_HEADER: "x-caig-auth"
      CAIG_WEBSVC_AUTH_VALUE: "K6ZQw!81"
      CAIG_WEB_APP_NAME: "caig-web"
      CAIG_GRAPH_SERVICE_URL: "http://graph_service"
      PORT: "8000"
      WEB_CONCURRENCY: 1

  graph_service:
    image: cjoakim/caig_graph_v2:latest
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_ACA_ENVIRONMENT_NAME: "caig-aca-poc-001"
      CAIG_AZURE_MONGO_VCORE_CONN_STR: ""
      CAIG_AZURE_OPENAI_COMPLETIONS_DEP: "gpt-4o"
      CAIG_AZURE_OPENAI_EMBEDDINGS_DEP: "text-embedding-3-small"
      CAIG_AZURE_OPENAI_KEY: "8a431f0899c740508a8ae5eb19284f8c"
      CAIG_AZURE_OPENAI_URL: "https://aoai-poc-eastus2-01.openai.azure.com/"
      CAIG_AZURE_REGION: "eastus2"
      CAIG_CONFIG_CONTAINER: "config"
      CAIG_CONVERSATIONS_CONTAINER: "conversations"
      CAIG_COSMOSDB_NOSQL_ACCT: "cosmos-caig-poc-991"
      CAIG_COSMOSDB_NOSQL_AUTH_MECHANISM: "key"
      CAIG_COSMOSDB_NOSQL_KEY1: "RmYKIdpIPQHIJOydtgIM592xPpapB1N1E0rGf67EPt4WveWcnrUBvduU0Lu5nLuaptqBB1fylfJpACDbMOR9Gw=="
      CAIG_COSMOSDB_NOSQL_RG: "rg-caig-poc-001"
      CAIG_COSMOSDB_NOSQL_URI: "https://cosmos-caig-poc-991.documents.azure.com:443/"
      CAIG_DEFINED_AUTH_USERS: ""
      CAIG_ENCRYPTION_SYMMETRIC_KEY: ""
      CAIG_FEEDBACK_CONTAINER: "feedback"
      CAIG_GRAPH_NAMESPACE: ""
      CAIG_GRAPH_SERVICE_NAME: ""
      CAIG_GRAPH_SERVICE_PORT: "8001"
      CAIG_GRAPH_SOURCE_CONTAINER: "libraries"
      CAIG_GRAPH_SOURCE_DB: "caig"
      CAIG_GRAPH_SOURCE_OWL_FILENAME: ""
      CAIG_GRAPH_SOURCE_RDF_FILENAME: ""
      CAIG_GRAPH_SOURCE_TYPE: "cosmos_nosql"
      CAIG_LA_WORKSPACE_NAME: ""
      CAIG_LOG_LEVEL: "debug"
      CAIG_WEBSVC_AUTH_HEADER: "x-caig-auth"
      CAIG_WEBSVC_AUTH_VALUE: "K6ZQw!81"
      CAIG_WEB_APP_NAME: "caig-web"
      CAIG_GRAPH_SERVICE_URL: "http://graph_service"
      PORT: "8000"
      WEB_CONCURRENCY: 1

# WEB_CONCURRENCY relates to uvicorn and the --workers count; see https://www.uvicorn.org
